services:
  postgres:
    image: postgres:15
    container_name: project_management_db
    environment:
      POSTGRES_DB: project_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot_network

  redis:
    image: redis:7-alpine
    container_name: project_management_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot_network

  bot:
    build: .
    container_name: project_management_bot
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - bot_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  bot_network:
    driver: bridge 