services:
  - type: web
    name: project-management-bot
    env: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DB_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PORT
        value: 3000
    autoDeploy: true

databases:
  - name: project-management-db
    plan: free
    databaseName: project_management
    user: postgres
